---
- name: Install Red Hat Satellite
  hosts: azure
  become: true

  tasks:
    - name: Remove RHUI repositories
      tags: repositories
      ansible.builtin.file:
        path: /etc/yum.repos.d/rh-cloud-base.repo
        state: absent

    - name: Register to Red Hat portal
      tags: repositories
      community.general.redhat_subscription:
        org_id: '{{ rhsm_org }}'
        activationkey: "{{ rhsm_activation_key }}"
        state: present

    - name: Disable all repositories
      tags: repositories
      community.general.rhsm_repository:
        name: "*"
        state: disabled

    - name: Enable required repositories
      tags: repositories
      community.general.rhsm_repository:
        name:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - satellite-6.15-for-rhel-8-x86_64-rpms
          - satellite-maintenance-6.15-for-rhel-8-x86_64-rpms
        state: enabled

    - name: Enable Satellite module
      tags: packages
      # Use command module to avoid module deps
      ansible.builtin.command: "dnf module enable -y satellite:el8"

    - name: Update to latest packages
      tags: packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install Satellite packages
      tags: packages
      ansible.builtin.yum:
        name: satellite
        state: present

    - name: Disable firewall
      tags: firewall
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false
